// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9XeHOlIK_yuPzLO3i02gB2T8IUdb5wLI',
    appId: '1:74449615104:web:f2191490aac93dc83a9be5',
    messagingSenderId: '74449615104',
    projectId: 'holkar-present',
    authDomain: 'holkar-present.firebaseapp.com',
    storageBucket: 'holkar-present.appspot.com',
    measurementId: 'G-XRF8YC9P6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-JIyzVHh0YMtTDt8gWQcGLshWuRZU7XA',
    appId: '1:74449615104:android:045c879fba1576bf3a9be5',
    messagingSenderId: '74449615104',
    projectId: 'holkar-present',
    storageBucket: 'holkar-present.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd4kBHnqOatMvPhFMnaELuOcPmLGxQH3Y',
    appId: '1:74449615104:ios:770d66fdff7e2c023a9be5',
    messagingSenderId: '74449615104',
    projectId: 'holkar-present',
    storageBucket: 'holkar-present.appspot.com',
    iosBundleId: 'com.example.holkarPresent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd4kBHnqOatMvPhFMnaELuOcPmLGxQH3Y',
    appId: '1:74449615104:ios:770d66fdff7e2c023a9be5',
    messagingSenderId: '74449615104',
    projectId: 'holkar-present',
    storageBucket: 'holkar-present.appspot.com',
    iosBundleId: 'com.example.holkarPresent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9XeHOlIK_yuPzLO3i02gB2T8IUdb5wLI',
    appId: '1:74449615104:web:5ccedfb9d5cb3f8c3a9be5',
    messagingSenderId: '74449615104',
    projectId: 'holkar-present',
    authDomain: 'holkar-present.firebaseapp.com',
    storageBucket: 'holkar-present.appspot.com',
    measurementId: 'G-6ECV5B06R5',
  );
}
